version: "3.8"
services:

  mongo:
    image: mongo
    restart: always
    networks:
      vpcbr:
        ipv4_address: 172.18.0.3
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    networks:
      vpcbr:
        ipv4_address: 172.18.0.4
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  fast-api:
    image: yannoushka/fast_api_p3:latest
    ports:
      - 8000:8000
    networks:
      vpcbr:
        ipv4_address: 172.18.0.5
    depends_on:
      - mongo
      - mongo-express
    environment:
      bdd_user: root
      bdd_password: exemple

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 172.18.0.0/16
         gateway: 172.18.0.1

  